# Generated by Django 5.2.1 on 2026-04-24 06:41

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_navmenu_navitem'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer settings',
            },
        ),
        migrations.CreateModel(
            name='FooterNavColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text="Column heading displayed above the links (e.g. 'Product', 'Company').", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(blank=True, help_text='Choose a nav menu whose items will appear as links in this column.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.navmenu')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_columns', to='cms.footersettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
